import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs/internal/Observable';
import { environment } from 'src/environments/environment';
import { McqGenerationDTO } from '@DTOs/question.dto';
import { OptionDTO } from '@DTOs/question.dto';

interface Answer {
  answer?: string;
  isCorrect?: boolean;
}
@Injectable({
  providedIn: 'root'
})
export class McqcreationService {

  constructor(private http: HttpClient) { }

  /**
   *
   * @param question
   * @param option
   * @param otherOptions
   * @param concept
   * @returns single autogenerated answer
   */
  getAnswer(
    question: string,
    option: OptionDTO,
    otherOptions: OptionDTO[],
    concept: string
  ): Observable<Answer> {
    const body = {
      question: question,
      option: option,
      otherOptions: otherOptions,
      concept: concept
    };
    return this.http.post<Answer>(environment.server + `/mcqcreation/answer`, body);
  }

  /**
   * Get the autogenerated answers for a given question
   * @param question The question to answer
   * @param options The number of options to generate
   * @returns autogenerated answers
   */
  getAnswers(question: string, options: number, concept: string) :Observable<McqGenerationDTO> {

    const body = new HttpParams()
      .set('question', question)
      .set('options', options)
      .set('concept', concept);

    return this.http.get<McqGenerationDTO>(environment.server + `/mcqcreation/answers`, {params: body})
  }

  /**
   *
   * @param concept
   * @param options
   * @returns generated question and answers
   */
  getQuestionAndAnswers(concept: string, options: number, topic: string = '') :Observable<McqGenerationDTO> {

      const body = new HttpParams()
        .set('concept', concept)
        .set('options', options)
        .set('topic', topic);
      return this.http.get<McqGenerationDTO>(environment.server + `/mcqcreation/questionAndAnswers`, {params: body})
  }

  /**
   *
   * @param question
   * @returns
   */
  getQuestionTitle(concept: string) :Observable<{question: string}> {
    const body = new HttpParams()
      .set('concept', concept);
    return this.http.get<{question: string}>(environment.server + `/mcqcreation/questionTitle`, {params: body})
  }


  /** NOT IMPLEMENTED
   * @param question
   * @param options
   * @param concept
   * @param answers
   * @returns evaluation of the answers
   */
  getEvaluation(question: string, options: number, concept: string, answers: string) :Observable<{mcq: McqGenerationDTO, reasoning: string}> {
    const body = new HttpParams()
      .set('question', question)
      .set('options', options)
      .set('concept', concept)
      .set('answers', answers);
    return this.http.get<{mcq: McqGenerationDTO, reasoning: string}>(environment.server + `/mcqcreation/evaluateOptions`, {params: body})
  }

  /** NOT IMPLEMENTED
   * @param question
   * @param options
   * @param concept
   * @param answers
   * @returns reevaluated question and answers
   */
  getReevaluatedQuestionAndAnswers(question: string, options: number, concept: string, answers: string) :Observable<{mcq: McqGenerationDTO, reasoning: string}> {
    const body = new HttpParams()
      .set('question', question)
      .set('options', options)
      .set('concept', concept)
      .set('answers', answers);
    return this.http.get<{mcq: McqGenerationDTO, reasoning: string}>(environment.server + `/mcqcreation/reevaluatedQuestionAndAnswers`, {params: body})
  }
}
