import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs/internal/Observable';
import { environment } from 'src/environments/environment';

interface Answer {
  answer?: string;
  correct?: boolean;
}
@Injectable({
  providedIn: 'root'
})
export class McqcreationService {

  constructor(private http: HttpClient) { }

  /**
   *
   * @param question
   * @param currentOption
   * @param otherOptions
   * @returns single autogenerated answer
   */
  getAnswer(question: string, currentOption: string, otherOptions: string, concept: string) :Observable<Answer> {

    const body = new HttpParams()
      .set('question', question)
      .set('option', currentOption)
      .set('otherOptions', otherOptions)
      .set('concept', concept);

    return this.http.get<Answer>(environment.server + `/mcqcreation/answer`, {params: body})
  }

  /**
   * Get the autogenerated answers for a given question
   * @param question The question to answer
   * @param options The number of options to generate
   * @returns autogenerated answers
   */
  getAnswers(question: string, options: number, concept: string) :Observable<{answers: Answer[], description: string, score: number}> {

    const body = new HttpParams()
      .set('question', question)
      .set('options', options)
      .set('concept', concept);

    return this.http.get<{answers: Answer[], description: string, score: number}>(environment.server + `/mcqcreation/answers`, {params: body})
  }

  /**
   *
   * @param concept
   * @param options
   * @returns generated question and answers
   */
  getQuestionAndAnswers(concept: string, options: number) :Observable<{question: string, answer: Answer[], description: string, score: number}> {

      const body = new HttpParams()
        .set('concept', concept)
        .set('options', options);
      return this.http.get<{question: string, answer: Answer[], description:string, score: number}>(environment.server + `/mcqcreation/questionAndAnswers`, {params: body})
  }

  /**
   * @param question
   * @param options
   * @param concept
   * @param answers
   * @returns reevaluated question and answers
   */
  getReevaluatedQuestionAndAnswers(question: string, options: number, concept: string, answers: string) :Observable<{question: string, answer: Answer[], reasoning: string}> {
    const body = new HttpParams()
      .set('question', question)
      .set('options', options)
      .set('concept', concept)
      .set('answers', answers);
    return this.http.get<{question: string, answer: Answer[], reasoning: string}>(environment.server + `/mcqcreation/reevaluatedQuestionAndAnswers`, {params: body})
  }

  /**
   * @param question
   * @param options
   * @param concept
   * @param answers
   * @returns evaluation of the answers
   */
  getEvaluation(question: string, options: number, concept: string, answers: string) :Observable<{answer: Answer[], reasoning: string}> {
    const body = new HttpParams()
      .set('question', question)
      .set('options', options)
      .set('concept', concept)
      .set('answers', answers);
    return this.http.get<{question: string, answer: Answer[], reasoning: string}>(environment.server + `/mcqcreation/evaluateOptions`, {params: body})
  }

  /**
   *
   * @param question
   * @returns
   */
  getQuestionTitle(concept: string) :Observable<{question?: string}> {
    const body = new HttpParams()
      .set('concept', concept);
    return this.http.get<{question?: string}>(environment.server + `/mcqcreation/questionTitle`, {params: body})
  }
}
