import { Annotation } from '@langchain/langgraph';
import { FeedbackContextDto } from '@DTOs/tutorKaiDtos/feedbackContext.dto';
import { FeedbackOutput } from './schemas/feedback-output.schema';

// Define the structure for lecture snippets if a more specific type is known, otherwise use 'any'
// Example:
// interface LectureSnippet {
//   source: string;
//   content: string;
//   score: number;
// }

/**
 * Defines the state object that flows through the Tutoring Feedback LangGraph.
 * Uses LangGraph's Annotation system for type safety and potential future features.
 */
export const TutoringFeedbackStateAnnotation = Annotation.Root({
  /** The initial input context containing student solution, task details, etc. */
  feedbackContext: Annotation<FeedbackContextDto>,

  /** The corrected version of the student's code generated by an LLM. */
  fixedCode: Annotation<string | null>({
    default: () => null,
    reducer: (current, update) => update ?? current, // Merge updates
  }),

  /** An array of relevant programming concepts extracted from the context. */
  concepts: Annotation<string[] | null>({
    default: () => null,
    reducer: (current, update) => update ?? current, // Merge updates
  }),

  /** Snippets of lecture material retrieved based on the extracted concepts. */
  /** Snippets of lecture material retrieved based on the extracted concepts. Stored as a JSON string matching KcAgent format. */
  lectureSnippets: Annotation<string | null>({
    default: () => null,
    reducer: (current, update) => update ?? current, // Merge updates
  }), // Replace 'any' with a specific type if available

  /** Map of citation placeholders ('$$1$$') to actual markdown links. */
  sourceMap: Annotation<Record<string, string> | null>({
    default: () => null,
    reducer: (current, update) => update ?? current, // Merge updates
  }),

  /** The ID of the GeneratedFeedback record created in the database. */
  generatedFeedbackId: Annotation<string | null>({
    default: () => null,
    reducer: (a, b) => b, // Replace old value with new
  }),

  /** The final structured feedback JSON generated by the last LLM call. */
  finalFeedbackJson: Annotation<FeedbackOutput | null>({
    default: () => null,
    reducer: (a, b) => b, // Default reducer: replace old value with new
  }),

  /** Optional field to store error messages during graph execution. */
  error: Annotation<string | null>({
    default: () => null,
    reducer: (current, update) => update ?? current, // Merge updates (keep existing error if new update doesn't have one)
  }),
});

// Type alias for the state object
export type TutoringFeedbackState =
  typeof TutoringFeedbackStateAnnotation.State;
