import { Controller, Post, Body, Req, Res } from '@nestjs/common';
import { LlmBasicPromptService } from '../services/llmBasicPrompt.service';
import { Response, Request } from 'express'; // Added Request import for type annotation
import { ChatBotRAGService } from './chatbot_rag.service';

@Controller('chat-bot')
export class ChatBotController {
  constructor(
    private readonly llmBasicPromptService: LlmBasicPromptService,
    private readonly chatBotRAGService: ChatBotRAGService
  ) {}

  /**
   * Endpoint to handle basic questions.
   * @param question The question asked by the user.
   * @returns The answer generated by the LLM.
   */
  @Post('ask/basic')
  async askBasic(@Body('question') question: string): Promise<{ answer: string }> {
    const answer = await this.llmBasicPromptService.generateLlmAnswer("Du bist ein hilfreicher Assistent.", question);
    return { answer: answer };
  }

  /**
   * Endpoint to handle dialog-based questions with streaming responses.
   * @param context The context of the ongoing conversation.
   * @param question The question asked by the user.
   * @param dialogSessionId The ID of the dialog session.
   * @param res The response object.
   * @param req The request object.
   */
  @Post('ask/basic/getStreamDialog')
  async askBasicWithStreamAnswerDialog(
    @Body('context') context: Array<{ role: string, content: string }>,
    @Body('question') question: string,
    @Body('dialogSessionId') dialogSessionId: string,
    @Res() res: Response,
    @Req() req
  ): Promise<void> {
    res.set('Content-Type', 'text/plain');
    res.setHeader('Transfer-Encoding', 'chunked');

    // Choose the appropriate response generation method based on the context length
    if (context.length > 3) { // 3 is the minimum and default number including the default question by the LLM
      await this.chatBotRAGService.chatBotRagAnswerDialog(context, question, res, req.user.id, dialogSessionId);
    } else {
      await this.chatBotRAGService.chatBotRagAnswer(question, res, req.user.id, dialogSessionId);
    }
  }
}
