/* eslint-disable prettier/prettier */
import { Controller, Post, Body, Req, Res, Get, HttpStatus, HttpException } from '@nestjs/common';
import { LlmBasicPromptService } from '../services/llmBasicPrompt.service';
import { Request, Response } from 'express';
import { ChatBotRAGService } from './chatbot_rag.service';
import { ChatBotMessageDTO } from '@DTOs/index';

interface RequestWithUser extends Request {
  user: {
    id: number;
  };
}

class RatingDto {
  messageId: number;
  rating: number;
}

@Controller('chat-bot')
export class ChatBotController {
  constructor(
    private readonly llmBasicPromptService: LlmBasicPromptService,
    private readonly chatBotRAGService: ChatBotRAGService
  ) {}

  /**
   * Endpoint to get all chat sessions for the current user.
   * @param req The request object containing user information.
   * @returns Array of chat sessions with their messages.
   */
  @Get('sessions')
  async getChatSessions(@Req() req: RequestWithUser) {
    try {
      return await this.chatBotRAGService.getChatSessions(req.user.id);
    } catch (error) {
      console.error('Error fetching chat sessions:', error);
      throw new HttpException('Error fetching chat sessions', HttpStatus.INTERNAL_SERVER_ERROR);
    }
  }

  /**
   * Endpoint to handle basic questions.
   * @param question The question asked by the user.
   * @returns The answer generated by the LLM.
   */
  @Post('ask/basic')
  async askBasic(@Body('question') question: string): Promise<{ answer: string }> {
    const answer = await this.llmBasicPromptService.generateLlmAnswer("Du bist ein hilfreicher Assistent.", question);
    return { answer: answer };
  }

  /**
   * Endpoint to handle dialog-based questions with streaming responses.
   * @param context The context of the ongoing conversation.
   * @param question The question asked by the user.
   * @param dialogSessionId The ID of the dialog session.
   * @param sessionId Optional ID of an existing chat session.
   * @param res The response object.
   * @param req The request object.
   */
  @Post('ask/basic/getStreamDialog')
  async askBasicWithStreamAnswerDialog(
    @Body('context') context: Array<{ role: string, content: string }>,
    @Body('question') question: string,
    @Body('dialogSessionId') dialogSessionId: string,
    @Req() req: RequestWithUser,
    @Res() res: Response,
    @Body('sessionId') sessionId?: number
  ): Promise<void> {
    res.set('Content-Type', 'text/plain');
    res.setHeader('Transfer-Encoding', 'chunked');

    // Choose the appropriate response generation method based on the context length
    if (context.length > 3) { // 3 is the minimum and default number including the default question by the LLM
      await this.chatBotRAGService.chatBotRagAnswerDialog(context, question, req.user.id, dialogSessionId, sessionId);
    } else {
      await this.chatBotRAGService.chatBotRagAnswer(question, req.user.id, dialogSessionId, sessionId);
    }
  }

  /**
   * Endpoint to handle dialog-based questions with non-streaming responses.
   * @param context The context of the ongoing conversation.
   * @param question The question asked by the user.
   * @param dialogSessionId The ID of the dialog session.
   * @param sessionId Optional ID of an existing chat session.
   * @param req The request object.
   * @returns The answer generated by the LLM and the message ID.
   */
  @Post('ask/basic/getDialog')
  async askBasicWithAnswerDialog(
    @Body('context') context: Array<{ role: string, content: string }>,
    @Body('question') question: string,
    @Body('dialogSessionId') dialogSessionId: string,
    @Req() req: RequestWithUser,
    @Body('sessionId') sessionId?: number
  ): Promise<ChatBotMessageDTO> {
    // Choose the appropriate response generation method based on the context length
    if (context.length > 3) { // 3 is the minimum and default number including the default question by the LLM
      return await this.chatBotRAGService.chatBotRagAnswerDialog(context, question, req.user.id, dialogSessionId, sessionId);
    } else {
      return await this.chatBotRAGService.chatBotRagAnswer(question, req.user.id, dialogSessionId, sessionId);
    }
  }

  /**
   * Endpoint to handle rating of chatbot messages.
   * @param ratingDto The rating data transfer object.
   * @param req The request object.
   * @returns A success message if the rating is saved successfully.
   */
  @Post('rate')
  async rateChatbotMessage(@Body() ratingDto: RatingDto, @Req() req: RequestWithUser): Promise<{ message: string }> {
    try {
      await this.chatBotRAGService.saveOrUpdateRating(ratingDto.messageId, ratingDto.rating, req.user.id);
      return { message: 'Rating saved successfully' };
    } catch (error) {
      console.error('Error saving rating:', error);
      throw new HttpException('Error saving rating', HttpStatus.INTERNAL_SERVER_ERROR);
    }
  }
}
