version: '3.1' 

services: 

# Postgres Database running in different compose

#ANGULAR
  hefl_client:
    container_name: goals_client
    build: 
      context: .
      dockerfile: ./Docker/angular
    ports: 
      - 4200:80
    networks:
      - nginx-network
    restart: always

#NestJS
  hefl_server:
    container_name: goals_server
    build: 
      context: .
      dockerfile: ./Docker/nest
    ports: 
      - 3000:3000
    networks:
      - nginx-network
    restart: always
    volumes:
    - ./files:/usr/src/files

networks:
  nginx-network:
    external: true