version: '3.1' 

services: 

# Postgres Database running in different compose

#ANGULAR
  hefl_aud_client:
    container_name: goals_aud_client
    build: 
      context: .
      dockerfile: ./Docker/angular
      args:
        # These values should be available as environment variables
        # when running 'docker-compose build' or 'docker-compose up --build'
        # They can be sourced from .env.prod
        WEBSITE_URL: ${WEBSITE_URL}
        SERVER_URL: ${SERVER_URL}
    networks:
      - nginx-network
    restart: always

#NestJS
  hefl_aud_server:
    container_name: goals_aud_server
    build: 
      context: .
      dockerfile: ./Docker/nest
    env_file:
      - .env # Contains non-sensitive vars like URLs, NODE_ENV (also used for build args)
      - .env.auth.prod # Contains sensitive vars like DB_URL, API keys
    networks:
      - nginx-network
    restart: always
    volumes:
    - ./files:/usr/src/files

networks:
  nginx-network:
    external: true