version: '3.8'

services:
  goals_production_db:
    container_name: goals_production_db
    hostname: goals_production_db
    image: ankane/pgvector
    command: postgres -c 'max_connections=1000'
    restart: always
    environment:
      POSTGRES_DB: production
      POSTGRES_USER: root
      POSTGRES_PASSWORD: DATABASE_ADMIN_PASSWORD # Replace or set in portainer
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - GOALS_PRODUCTION_DATA:/var/lib/postgresql/data  # Persistent data volume
    ports:
      - "4000:5432" # Port 4000 is blocked by ZIMT, so internally we can use it for the backupservice without risking to expose it to the internet.
    networks:
      - nginx-network

  goals_production_pgadmin:
    container_name: goals_production_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kontakt@svenjacobs.de
      PGADMIN_DEFAULT_PASSWORD: PG_ADMIN_PASSWORD # Replace or set in portainer
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true

volumes:
  GOALS_PRODUCTION_DATA: