version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: ./Docker/server
    container_name: lecturelinker_server
    ports:
      - 3000:3000
    volumes:
      - /code/server/storage
    networks:
      - nginx-network

  angular:
    build: 
      context: .
      dockerfile: ./Docker/angular
    container_name: lecturelinker_client
    ports: 
      - 37000:80
    networks:
      - nginx-network
    restart: always


networks:
  nginx-network:
    external: true