import { Component, OnInit,ViewChild } from '@angular/core';
import { FormGroup, Validators, FormArray, FormControl } from '@angular/forms';
import { QuestionDataService } from 'src/app/Services/question/question-data.service';
import { McQuestionDTO, QuestionDTO, QuestionVersionDTO, MCOptionDTO } from '@DTOs/question.dto';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatDialog } from '@angular/material/dialog';
import { Observable, of, switchMap, throwIfEmpty, Subscriber, startWith, map, min, max } from 'rxjs';
import { McQuestionOptionDTO } from '@DTOs/question.dto';
import { CdkTextareaAutosize } from '@angular/cdk/text-field';
import { ProgressSpinnerMode } from '@angular/material/progress-spinner';
import { ScoreComponent } from './score/score.component';
import { MatSnackBar } from '@angular/material/snack-bar';
import { DescriptionDialogComponent } from './description-dialog/description-dialog.component';
import { McqcreationService } from 'src/app/Services/mcqCreation/mcqcreation.service';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { ContentService } from 'src/app/Services/content/content.service';
import { ConceptNodeDTO } from '@DTOs/conceptNode.dto';

interface Answer {
  answer?: string;
  correct?: boolean;
}



@Component({
  selector: 'app-mc-task-creation',
  templateUrl: './mc-task-creation.component.html',
  styleUrls: ['./mc-task-creation.component.scss'],
})
export class McTaskCreationComponent implements OnInit /*,OnChanges*/ {
  editorConfig = { //tinyMCE
    readonly: false,
    plugins: 'autoresize lists table link image code codesample',
    toolbar: false,
    min_height: 100,
    max_height: 500,
    min_width: 300,
    max_width: 500,
    resize: false,
  }
  questions: QuestionDTO[] = [];
  taskForm: FormGroup;
  placeholder:string = "Option "
  disabled: boolean = true;
  @ViewChild('autosize') autosize: CdkTextareaAutosize | undefined;


  //spinner
  // color: ThemePalette = 'primary';
  // mode: ProgressSpinnerMode = 'indeterminate';
  // value = 50;

  // dtos for making backend calls for creating a Question, Options, McQuestion and QuestionVersion
  questionData: QuestionDTO = {
    id: -1,
    name: '',
    description: '',
    // setting author based on some kind of user service?
    author: 1,
    score: 0,
    type: '',
    text: '',
  } as QuestionDTO;
  versionData: QuestionVersionDTO = {
        id: 1,
        version: 1,
        isApproved: false,
        successor: null,

  } as QuestionVersionDTO;

  mcQuestion: McQuestionDTO = {
    id: -1,
    questionId: -1,
    questionVersion: this.versionData,
    isSC: false,
    shuffleOptions: false,
  } as McQuestionDTO;

  McQuestionOption: McQuestionOptionDTO = {} as McQuestionOptionDTO;


  questionId: number = 1;
  // init with true, because unchecked box means single choice and is default
  isSC: string | undefined;
  mcOptions: MCOptionDTO[] = [] as MCOptionDTO[];

  // for chatmodel interaction

  autogeneratedAnswers$!: Observable<{ answer?: string; correct?: boolean; }[]>;
  reevaluatedQuestionAndAnswers$!: Observable<{ question: string; answer: Answer[], reasoning: string; }[]>;
  evaluation$!: Observable<{ answer: Answer[], reasoning: string; }>;
  autogenasnwers: { answer?: string; correct?: boolean; }[] = [] ;
  mcDisabled: boolean = false;
  color: string = "warn"


  concepts: string[] = []
  currentConcept!: string;
  conceptControl = new FormControl();
  filteredConcepts: Observable<string[]> | undefined;

  setScore: boolean = false;
  fetchingTitle: boolean = false;
  fetchingStates: boolean[] = [false, false, false, false, false, false];
  Questiontitle: string = "";

  constructor(
    private questionService : QuestionDataService,
    private dialog: MatDialog,
    private _snackBar: MatSnackBar,
    private mcqService: McqcreationService,
    private contentService: ContentService) {
    this.taskForm = new FormGroup({
      'title': new FormControl(null, Validators.required),
      'numberOfOptions': new FormControl(4, [Validators.required]),
      'description': new FormControl(null),
      'score': new FormControl(null, Validators.required),
      'type': new FormControl('', Validators.required),
      // author: ['', Validators.required],
      'options': new FormArray([],[Validators.required, Validators.min(2)]),
      'conceptName': new FormControl('', Validators.required),
      //'text': new FormControl(['', Validators.required, Validators.min(1)]),
    });
  }

  ngOnInit(): void {
    this.updateOptions(this.taskForm.get('numberOfOptions')?.value);
    this.onChanges();
    this.contentService.fetchAllConceptNames().subscribe(concepts => {
      concepts.forEach(concept => {
        this.concepts.push(concept);
      });
    });
    this.filteredConcepts = (this.taskForm.get('conceptName'))?.valueChanges
      .pipe(
        startWith(''),
        map(value => this._filter(value))
      )

    console.log("concepts: ",this.filteredConcepts)
  }

  private _filter(value: string): string[] {
    const filterValue = value.toLowerCase();
    if(!filterValue){
      return this.concepts;
    }
    return this.concepts.filter(concept => concept.toLowerCase().includes(filterValue));
  }

  /**
   * Method to be called when values will change
   */
  onChanges(): void {
    this.Questiontitle = this.taskForm.get('title')?.value;
    this.taskForm.get('text')?.valueChanges.subscribe(val => {
      this.Questiontitle = val;
    });
    this.taskForm.get('numberOfOptions')?.valueChanges.subscribe((value) => {
      this.updateOptions(value);;
    });
    this.getOptions().valueChanges.subscribe((value) => {
      this.updateIsSC();
      this.countCorrectOptions();
    });

  }

  /**
  *
  * @param numberOfOptions
  * sets the amount of available input fields to numberOfOptions
  */
  updateOptions(numOfOptions: number) {

    if(this.taskForm.get('numberOfOptions')?.value < 0) {
      this.taskForm.get('numberOfOptions')?.setValue(0);
    }
   const options = this.taskForm.get('options') as FormArray;
    const numberOfOptions = this.taskForm.get('numberOfOptions')?.value;

    if(numberOfOptions < 0 || numOfOptions === null){
      this.taskForm.get('numberOfOptions')?.setValue(0);
      return;
    }
  // Überprüfen, ob numberOfOptions größer als 6 ist
    if (numberOfOptions > 6) {
      // Setzen Sie numberOfOptions auf 6, wenn es größer als 6 ist
      this.taskForm.get('numberOfOptions')?.setValue(6);
      // Zeigen Sie eine Warnmeldung an
      alert('Sie können nicht mehr als 6 Optionen hinzufügen');
      return;
    }

    while (options.length !== numberOfOptions) {
      if (options.length < numberOfOptions) {
        options.push(new FormGroup({
          text: new FormControl('', Validators.required),
          isCorrect: new FormControl(false, Validators.required)
        }));
      } else {
        options.removeAt(options.length - 1);
      }

  }


  }

  getOptions(): FormArray {
    return this.taskForm.get('options') as FormArray;
  }

  clearTitle() {
    this.taskForm.get('title')?.setValue('');

  }

  generateTitle() {
    if(!this.taskForm.get('conceptName')?.value) {
      this._snackBar.open('You need to enter a Concept', 'Close', {
        duration: 5000,
      });
    }
    console.log("title fired")
    console.log("concept", this.taskForm.get('conceptName')?.value)
    if(this.taskForm.get('conceptName')?.value) {
      console.log("title fired again: ")
      this.fetchingTitle = true;
      this.mcqService.getQuestionTitle(this.taskForm.get('conceptName')?.value).subscribe(
        (question: string) => {
          this.taskForm.get('title')?.setValue(question);
          this.fetchingTitle = false;
          console.log("Lol")
        }
      )
      console.log("lol")
    }
  }

  getButtonLabel(index: number) {
    const option = this.getOptions().at(index) as FormControl;
    return option.get('text')?.value ? 'Regenerate' : 'Generate Answer';
  }

  clearOption(index: number) {
    const option = this.getOptions().at(index) as FormControl;
    option.get('text')?.setValue('');
  }

  updateIsSC() {
    if(this.getOptions().controls.filter(control => control.get('isCorrect')?.value === true).length > 1) {
      this.mcDisabled = true;
      this.taskForm.get("type")?.setValue("MC");
    } else if (this.getOptions().controls.filter(control => control.get('isCorrect')?.value === true).length === 1) {
      this.mcDisabled = false;
      this.taskForm.get("type")?.setValue("SC");
    } else if (this.getOptions().controls.filter(control => control.get('isCorrect')?.value === true).length === 0) {
      this.mcDisabled = false;
      this.taskForm.get("type")?.setValue("");
    }
    //this.taskForm.get("type")?.setValue(numberOfCorrectOptions > 1 ? "MC" : "SC");
  }

  generate() {
    const title = this.taskForm.get('title')?.value
    const numberOfOptions = this.taskForm.get('numberOfOptions')?.value
    if(title && numberOfOptions) {
      this.generateOptions()
    } else {
      if(!title && numberOfOptions) {
        this.fetchingTitle = true;
        this.generateQuestionAndOptions();
      }
    }
  }

  onConceptSelected(event: any) {
    this.currentConcept! = event;
    console.log("concept: ",event)
  }

  generateQuestionAndOptions() {
    const numberOfOptions = this.taskForm.get('numberOfOptions')?.value
    // change to dynamically get concept from dropdown
    console.log(this.taskForm.get('conceptName')?.value)
    const concept = this.taskForm.get('conceptName')?.value
    if(concept && numberOfOptions) {
      for(let i = 0; i < this.getOptions().length; i++) {
        const option = (this.getOptions().at(i) as FormGroup);
        this.fetchingStates[i] = !option.get('text')?.value;
      }
      this.mcqService.getQuestionAndAnswers(concept, numberOfOptions).subscribe(
        (questionAndAnswers: { question: string; answer: Answer[], description: string, score: number; }) => {
          this.taskForm.get('title')?.setValue(questionAndAnswers.question);
          this.autogeneratedAnswers$ = of(questionAndAnswers.answer);
          this.autogeneratedAnswers$.subscribe( answers => {
            console.log("answers: ",answers)
            this.taskForm.get('description')?.setValue(questionAndAnswers.description);
            this.taskForm.get('score')?.setValue(questionAndAnswers.score);
            for (let i = 0; i < this.getOptions().length; i++) {
              const option = (this.getOptions().at(i) as FormGroup);
              option.get('text')?.setValue(answers[i].answer);
              option.get('isCorrect')?.setValue(answers[i].correct);

              this.fetchingStates[i] = false;
            }
            this.fetchingTitle = false;

          })
        })

    } else {
      alert("Please enter a concept and the number of options")
    }
  }

  generateOptions(){
    const title = this.taskForm.get('title')?.value
    let emptyOptions = 0;
    const concept = this.taskForm.get('conceptName')?.value
    for(let i = 0; i < this.getOptions().length; i++) {
      const option = (this.getOptions().at(i) as FormGroup);
      if(!option.get('text')?.value) {
        emptyOptions++;
      }
    }
    if(title) {
      for(let i = 0; i < this.getOptions().length; i++) {
        const option = (this.getOptions().at(i) as FormGroup);
        this.fetchingStates[i] = !option.get('text')?.value;
      }
      this.mcqService.getAutogeneratedAnswers(title, emptyOptions, concept).subscribe(
        (answers: { answer?: string; correct?: boolean; }[]) => {
          this.autogeneratedAnswers$ = of(answers);
          console.log("autogeneratedAnswers: ",this.autogeneratedAnswers$)
          this.autogeneratedAnswers$.subscribe( answers => {
            let answerIndex = 0;
            for (let i = 0; i < this.getOptions().length; i++) {
              const option = (this.getOptions().at(i) as FormGroup);
              if(!option.get('text')?.value) {
                option.get('text')?.setValue(answers[answerIndex].answer);
                option.get('isCorrect')?.setValue(answers[answerIndex].correct);
                answerIndex++;
              }
              this.fetchingStates[i] = false;
            }
          })
        }
      )
    }
  }

  generateOption(index: number) {
    const option = (this.getOptions().at(index) as FormGroup).get('text');
    const isCorrect = (this.getOptions().at(index) as FormGroup).get('isCorrect');
    const opt = option!.value;
    const title = this.taskForm.get('title')?.value
    const concept = this.taskForm.get('conceptName')?.value
    let otherOpts = ""
    for (let i = 0; i < this.getOptions().length; i++) {
      if (i !== index) {
        const otherOption = (this.getOptions().at(i) as FormGroup).get('text');
        otherOpts = otherOpts.concat(otherOption?.value + " ");
      }
    }

    console.log("otherOptions: ",otherOpts);
    if(title) {
      option?.setValue('');
      this.fetchingStates[index] = true;
      console.log("option before sending: ",opt)
      this.mcqService.getAutogeneratedAnswer(title, opt, otherOpts, concept).subscribe(
        (answer: { answer?: string; correct?: boolean; }) => {
          option?.setValue(answer.answer);
          isCorrect?.setValue(answer.correct);
          this.fetchingStates[index] = false;
        }
      )
    }
  }


  checkDescription(): boolean {
    return this.taskForm.get('description')?.value != null;
  }

  checkScore(): boolean {
    // this.color = "primary";
    return this.taskForm.get("score")?.value != null;
  }

  clearAllFields() {
    this.taskForm.get('title')?.setValue('');
    this.taskForm.get('description')?.setValue('');
    this.taskForm.get('score')?.setValue('');
    this.taskForm.get('type')?.setValue('');
    this.taskForm.get('options')?.reset();
  }

  // NOT IMPLEMENTED: automatic evaluation of the question
  evaluate() {
    const title = this.taskForm.get('title')?.value
    const numberOfOptions = this.taskForm.get('numberOfOptions')?.value
    const concept = "Anweisungen und Ausdrücke" //getConcept()
    let answers = ""
    for (let i = 0; i < this.getOptions().length; i++) {
      const otherOption = (this.getOptions().at(i) as FormGroup).get('text');
      answers = answers.concat(otherOption?.value + " ");
    }
    if(title && numberOfOptions) {
      this.mcqService.getEvaluation(title, numberOfOptions, concept, answers).subscribe(
        (answers: {answer: Answer[], reasoning: string}) => {
          this.evaluation$ = of(answers);
          console.log("autogeneratedAnswers: ",this.evaluation$)
          this.evaluation$.subscribe(answers => {
            console.log("evaluation answers: ",answers)
            for (let i = 0; i < this.getOptions().length; i++) {
              const option = (this.getOptions().at(i) as FormGroup);
              option.get('isCorrect')?.setValue(answers.answer[i].correct);
            }
          })
        }
      )
    }
  }

  reevaluate() {
    const title = this.taskForm.get('title')?.value
    const concept = "Anweisungen und Ausdrücke" //getConcept()
    let answers = ""
    for (let i = 0; i < this.getOptions().length; i++) {
      const otherOption = (this.getOptions().at(i) as FormGroup).get('text');
      answers = answers.concat(otherOption?.value + " ");
    }
    let emptyOptions = 0;
    for(let i = 0; i < this.getOptions().length; i++) {
      const option = (this.getOptions().at(i) as FormGroup);
      if(!option.get('text')?.value) {
        emptyOptions++;
      }
    }
    if(title) {
      for(let i = 0; i < this.getOptions().length; i++) {
        const option = (this.getOptions().at(i) as FormGroup);
        this.fetchingStates[i] = !option.get('text')?.value;
      }
      this.mcqService.getReevaluatedQuestionAndAnswers(title, emptyOptions, concept, answers).subscribe(
        (answers:{question: string, answer: Answer[], reasoning: string}) => {
          this.reevaluatedQuestionAndAnswers$ = of([answers]);
          console.log("autogeneratedAnswers: ",this.reevaluatedQuestionAndAnswers$)
          this.reevaluatedQuestionAndAnswers$.subscribe( answers => {
            let answerIndex = 0;
            for (let i = 0; i < this.getOptions().length; i++) {
              const option = (this.getOptions().at(i) as FormGroup);
              if(!option.get('text')?.value) {
                option.get('text')?.setValue(answers[answerIndex].answer[i].answer);
                option.get('isCorrect')?.setValue(answers[answerIndex].answer[i].correct);
                answerIndex++;
              }
              this.fetchingStates[i] = false;
            }
          })
        }
      )
    }
  }

  // method to open the dialogbox for adding score
  openDialog(): void {
    const dialogRef = this.dialog.open(ScoreComponent, {
      height: '270px',
      width: '270px',
      data: { score: this.taskForm.get('score')?.value }
    });

    dialogRef.afterClosed().subscribe(result => {
      console.log('The dialog was closed');
       this.taskForm.get('score')?.setValue(result);
       console.log("score: ",this.taskForm.get('score')?.value);


    });
  }
  // method to open the dialogbox for adding description
  openDescripDialog(): void {
    const dialogRef = this.dialog.open(DescriptionDialogComponent, {
      height: '320px',
      width: '320px',
      data: { description: this.taskForm.get('description')?.value }
    });

    dialogRef.afterClosed().subscribe(result => {
      console.log('The dialog was closed');
      this.taskForm.get('description')?.setValue(result);
      console.log("Description: ",this.taskForm.get('description')?.value);
    });
  }

  onCheckboxChange(event: MatCheckboxChange) {
    this.isSC = event.checked ? 'MC' : 'SC';

  }

  getCorrectOptionsCount() {
    return this.getOptions().value.map((option: { isCorrect: boolean; }) => option.isCorrect).filter((v: number) => v).length;
  }

  countCorrectOptions() {
    let correctOptions = 0;
    for (let option of this.mcOptions) {
      if (option.isCorrect) {
        correctOptions++;
      }
    }

    if(correctOptions >= 2) {
      this.mcDisabled = true;
    }
  }

  onSubmit(): void {

    if(this.taskForm.valid) {



      const formQuestionData: QuestionDTO = {
        author: 1, // need to set the author on some kind of user service
        description: this.taskForm.get('description')?.value,
        score: this.taskForm.get('score')?.value,
        type: this.taskForm.get('type')?.value,
        text: this.taskForm.get('title')?.value,// need to set the author on some kind of user service
        conceptNodeName: this.taskForm.get('conceptName')?.value,

        //conceptNode: this.taskForm.get('conceptNode or conceptElement')?.value, because of dropdown


      } as QuestionDTO;

      console.log("formData: ",formQuestionData);

      // setting the mcOptions from the options control array
      this.mcOptions = this.taskForm.get('options')?.value;

      // create question to get id and afterwards creating the (questionverion + options + McQuestion) entries (?)
      // make the other calls within the createquestion call? question -> questionversion -> mcquestion -> options (?)
      // ToDo: setting authorId

      // creating options can be done independently from the others based on the options control array
      this.questionService.createOptions(this.mcOptions).subscribe(options => {
        this.mcOptions = options;
        console.log("mcOptions after creating: ",this.mcOptions)
       });
      console.log("mcOptions: ",this.mcOptions);

      // creating question database entry first to get the questionId for following calls
      // using switchMap to concatenate the calls
      this.questionService.createQuestion(formQuestionData).pipe(

        // having version ready, we can create the mcquestion database entry (?)
        switchMap((questionResponse: QuestionDTO): Observable<McQuestionDTO> => {
          if(questionResponse.id) {
            this.mcQuestion.questionId = questionResponse.id;
            this.mcQuestion.shuffleOptions = true;
            return this.questionService.createMcQuestion(this.mcQuestion);
          } else {
            throw new Error("QuestionVersionId is undefined");
          }

        })
      )
      // creating the McQuestionOption entries for linking (?)
      .subscribe((mcQuestion: McQuestionDTO) => {
        console.log("mcQuestionOptionDTO: ",this.McQuestionOption);
        console.log("mcQuestion: ",mcQuestion);
        this.mcOptions.forEach(option => {
          console.log("option: ",option);
          this.McQuestionOption.mcQuestion = mcQuestion;
          this.McQuestionOption.mcOption = option;
          this.questionService.createMcQuestionOption(this.McQuestionOption).subscribe(

          );
        });
      });

      console.log("questionOptions again: ",this.McQuestionOption);

      this.resetTaskForm();
      // Snackbar öffnen
      this._snackBar.open('Saved a new Question', 'Close', {
        duration: 5000,
      });
    }
  }
  resetTaskForm(): void {
    const questionValue = this.taskForm.get('title')?.value;
    this.taskForm.reset();
    this.taskForm.get('title')?.setValue(questionValue);
  }

}


