import { OnInit, Component, ViewChild } from '@angular/core';
import { AbstractControl, FormGroup, Validators, FormArray, FormControl } from '@angular/forms';
import { QuestionDataService } from 'src/app/Services/question/question-data.service';
import {
  McQuestionDTO,
  QuestionDTO,
  QuestionVersionDTO,
  MCOptionDTO,
  McqGenerationDTO,
  OptionDTO,
} from '@DTOs/question.dto';
import { MatDialog } from '@angular/material/dialog';
import { Observable } from 'rxjs';
import { of, switchMap, startWith, map, max } from 'rxjs';
import { McQuestionOptionDTO } from '@DTOs/question.dto';
import { CdkTextareaAutosize } from '@angular/cdk/text-field';
import { MCScoreComponent } from './score/score.component';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MCDescriptionDialogComponent } from './description-dialog/description-dialog.component';
import { McqcreationService } from 'src/app/Services/mcqCreation/mcqcreation.service';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { ContentService } from 'src/app/Services/content/content.service';
import {
  Answer,
  McqEvaluation,
  McqEvaluations,
} from 'src/app/Services/mcqCreation/mcqcreation.types';

@Component({
  selector: 'app-mc-task-creation',
  templateUrl: './mc-task-creation.component.html',
  styleUrls: ['./mc-task-creation.component.scss'],
})
export class McTaskCreationComponent implements OnInit {
  editorConfig = {
    readonly: false,
    plugins: 'autoresize lists table link image code codesample',
    toolbar: false,
    min_height: 100,
    max_height: 500,
    min_width: 300,
    max_width: 500,
    resize: false,
  };
  questions: QuestionDTO[] = [];
  taskForm: FormGroup;
  placeholder: string = 'Option ';
  disabled: boolean = true;
  @ViewChild('autosize') autosize: CdkTextareaAutosize | undefined;

  questionData: QuestionDTO = {
    id: -1,
    name: '',
    description: '',
    author: 1,
    score: 0,
    type: '',
    text: '',
  } as QuestionDTO;
  versionData: QuestionVersionDTO = {
    id: 1,
    version: 1,
    isApproved: false,
    successor: null,
  } as QuestionVersionDTO;

  mcQuestion: McQuestionDTO = {
    id: -1,
    questionId: -1,
    questionVersion: this.versionData,
    isSC: false,
    shuffleOptions: false,
    mcQuestionOption: [],
  };

  mcQuestionOption: McQuestionOptionDTO = {} as McQuestionOptionDTO;

  questionId: number = 1;
  isSC: string | undefined;
  mcOptions: MCOptionDTO[] = [] as MCOptionDTO[];

  autogeneratedAnswers$?: Observable<McqGenerationDTO>;
  autogeneratedQuestionAndAnswers$?: Observable<McqGenerationDTO>;
  reevaluatedQuestionAndAnswers$!: Observable<{ mcq: McqGenerationDTO; reasoning: string }[]>;
  evaluation$?: Observable<McqEvaluations>;
  mcDisabled: boolean = false;
  color: string = 'warn';
  concepts: string[] = [];
  conceptControl = new FormControl();
  filteredConcepts: Observable<string[]> | undefined;
  setScore: boolean = false;
  fetchingTitle: boolean = false;
  fetchingStates: boolean[] = [false, false, false, false, false, false];
  Questiontitle: string = '';
  immediateGeneration: boolean = false;

  constructor(
    private readonly questionService: QuestionDataService,
    private readonly dialog: MatDialog,
    private readonly _snackBar: MatSnackBar,
    private readonly mcqService: McqcreationService,
    private readonly contentService: ContentService,
  ) {
    this.taskForm = new FormGroup({
      title: new FormControl(null, Validators.required),
      numberOfOptions: new FormControl(4, [Validators.required]),
      description: new FormControl(null),
      score: new FormControl(null, Validators.required),
      type: new FormControl('', Validators.required),
      options: new FormArray([], [Validators.required, Validators.min(2)]),
      conceptName: new FormControl('', Validators.required),
    });
  }

  ngOnInit(): void {
    this.updateOptions(this.taskForm.get('numberOfOptions')?.value);
    this.onChanges();
    this.contentService.fetchAllConceptNames().subscribe(concepts => {
      concepts.forEach(concept => {
        this.concepts.push(concept);
      });
    });
    this.filteredConcepts = this.taskForm.get('conceptName')?.valueChanges.pipe(
      startWith(''),
      map(value => this.filter(value)),
    );
  }

  private filter(value: string): string[] {
    const filterValue = value.toLowerCase();
    if (!filterValue) {
      return this.concepts;
    }
    return this.concepts.filter(concept => concept.toLowerCase().includes(filterValue));
  }

  onChanges(): void {
    this.Questiontitle = this.taskForm.get('title')?.value;
    this.taskForm.get('text')?.valueChanges.subscribe(val => {
      this.Questiontitle = val;
    });
    this.taskForm.get('numberOfOptions')?.valueChanges.subscribe(value => {
      this.updateOptions(value);
    });
    this.getOptions().valueChanges.subscribe(value => {
      this.updateIsSC();
      this.countCorrectOptions();
    });
  }

  updateOptions(numOfOptions: number): void {
    if (this.taskForm.get('numberOfOptions')?.value < 0) {
      this.taskForm.get('numberOfOptions')?.setValue(0);
    }
    const options = this.taskForm.get('options') as FormArray;
    const numberOfOptions = this.taskForm.get('numberOfOptions')?.value;

    if (numberOfOptions < 0 || numOfOptions === null) {
      this.taskForm.get('numberOfOptions')?.setValue(0);
      return;
    }
    if (numberOfOptions > 6) {
      this.taskForm.get('numberOfOptions')?.setValue(6);
      alert('Sie können nicht mehr als 6 Optionen hinzufügen');
      return;
    }

    while (options.length !== numberOfOptions) {
      if (options.length < numberOfOptions) {
        options.push(
          new FormGroup({
            text: new FormControl('', Validators.required),
            correct: new FormControl(false, Validators.required),
          }),
        );
      } else {
        options.removeAt(options.length - 1);
      }
    }
  }

  getOptions(): FormArray {
    return this.taskForm.get('options') as FormArray;
  }

  clearTitle(): void {
    this.taskForm.get('title')?.setValue('');
  }

  titleAndNumberOfOptionsFilled(): boolean {
    return (
      this.taskForm.get('title')?.value != null &&
      this.taskForm.get('numberOfOptions')?.value != null
    );
  }

  generateTitle(): void {
    if (!this.taskForm.get('conceptName')?.value) {
      this._snackBar.open('You need to enter a Concept', 'Close', {
        duration: 5000,
      });
    }
    if (this.taskForm.get('conceptName')?.value) {
      this.fetchingTitle = true;
      this.mcqService
        .getQuestionTitle(this.taskForm.get('conceptName')?.value)
        .subscribe((questionTitle: { question: string }) => {
          this.taskForm.get('title')?.setValue(questionTitle.question);
          this.fetchingTitle = false;
        });
    }
  }

  getButtonLabel(index: number): string {
    const option = this.getOptions().at(index) as FormControl;
    return option.get('text')?.value ? 'Regenerate' : 'Generate Answer';
  }

  clearOption(index: number): void {
    const option = this.getOptions().at(index) as FormControl;
    option.get('text')?.setValue('');
  }

  updateIsSC(): void {
    if (
      this.getOptions().controls.filter(control => control.get('correct')?.value === true).length >
      1
    ) {
      this.mcDisabled = true;
      this.taskForm.get('type')?.setValue('MC');
    } else if (
      this.getOptions().controls.filter(control => control.get('correct')?.value === true)
        .length === 1
    ) {
      this.mcDisabled = false;
      this.taskForm.get('type')?.setValue('SC');
    } else if (
      this.getOptions().controls.filter(control => control.get('correct')?.value === true)
        .length === 0
    ) {
      this.mcDisabled = false;
      this.taskForm.get('type')?.setValue('');
    }
  }

  generate(): void {
    const title = this.taskForm.get('title')?.value;
    const numberOfOptions = this.taskForm.get('numberOfOptions')?.value;
    if (title && numberOfOptions) {
      this.generateOptions();
    } else {
      if (!title && numberOfOptions) {
        this.fetchingTitle = true;
        this.generateQuestionAndOptions();
      }
    }
  }

  generateQuestionAndOptions(): void {
    const numberOfOptions = this.taskForm.get('numberOfOptions')?.value;
    const concept = this.taskForm.get('conceptName')?.value;
    if (concept && numberOfOptions) {
      for (let i = 0; i < this.getOptions().length; i++) {
        const option = this.getOptions().at(i) as FormGroup;
        this.fetchingStates[i] = !option.get('text')?.value;
      }
      this.mcqService
        .getQuestionAndAnswers(concept, numberOfOptions)
        .subscribe((questionAndAnswers: McqGenerationDTO) => {
          this.taskForm.get('title')?.setValue(questionAndAnswers.question);
          this.autogeneratedQuestionAndAnswers$ = of(questionAndAnswers);
          this.autogeneratedQuestionAndAnswers$.subscribe(answers => {
            this.taskForm.get('description')?.setValue(questionAndAnswers.description);
            this.taskForm.get('score')?.setValue(questionAndAnswers.score);

            for (let i = 0; i < this.getOptions().length; i++) {
              const option = this.getOptions().at(i) as FormGroup;
              option.get('text')?.setValue(answers.answers?.[i].answer);
              option.get('correct')?.setValue(answers.answers?.[i].correct);
              this.fetchingStates[i] = false;
            }
            this.fetchingTitle = false;
          });
        });
    } else {
      alert('Please enter a concept and the number of options');
    }
  }

  generateOptions(): void {
    const title = this.taskForm.get('title')?.value;
    let emptyOptions = 0;
    const concept = this.taskForm.get('conceptName')?.value;
    for (let i = 0; i < this.getOptions().length; i++) {
      const option = this.getOptions().at(i) as FormGroup;
      if (!option.get('text')?.value) {
        emptyOptions++;
      }
    }
    if (title && concept) {
      for (let i = 0; i < this.getOptions().length; i++) {
        const option = this.getOptions().at(i) as FormGroup;
        this.fetchingStates[i] = !option.get('text')?.value;
      }
      this.mcqService
        .getAnswers(title, emptyOptions, concept)
        .subscribe((answers: McqGenerationDTO) => {
          this.autogeneratedAnswers$ = of(answers);
          this.autogeneratedAnswers$.subscribe(answers => {
            for (let i = 0; i < this.getOptions().length; i++) {
              const option = this.getOptions().at(i) as FormGroup;
              option.get('text')?.setValue(answers.answers?.[i].answer);
              option.get('correct')?.setValue(answers.answers?.[i].correct);
              this.fetchingStates[i] = false;
            }
          });
        });
    } else {
      alert('Please enter a Title, concept and the number of options');
    }
  }

  generateOption(index: number): void {
    const optionControl = this.getOptions().at(index) as FormGroup;
    const optionTextControl = optionControl.get('text')!;
    const optionCorrectControl = optionControl.get('correct')!;

    const currentOption: OptionDTO = {
      answer: optionTextControl.value || '',
      correct: optionCorrectControl.value || false,
    };

    const title = this.taskForm.get('title')?.value;
    const concept = this.taskForm.get('conceptName')?.value;

    const otherOptions: OptionDTO[] = this.getOptions()
      .controls.filter((_, i) => i !== index)
      .map((control: AbstractControl) => {
        const optGroup = control as FormGroup;
        return {
          answer: optGroup.get('text')?.value || '',
          correct: optGroup.get('correct')?.value || false,
        };
      });

    if (title) {
      optionTextControl.setValue('');
      this.fetchingStates[index] = true;

      this.mcqService
        .getAnswer(title, currentOption, otherOptions, concept)
        .subscribe((answer: Answer) => {
          optionTextControl.setValue(answer.answer);
          optionCorrectControl.setValue(answer.correct);
          this.fetchingStates[index] = false;
        });
    }
  }

  checkDescription(): boolean {
    return this.taskForm.get('description')?.value != null;
  }

  checkScore(): boolean {
    return this.taskForm.get('score')?.value != null;
  }

  clearAllFields(): void {
    this.taskForm.get('title')?.setValue('');
    this.taskForm.get('description')?.setValue('');
    this.taskForm.get('score')?.setValue('');
    this.taskForm.get('type')?.setValue('');
    this.taskForm.get('options')?.reset();
    this.taskForm.get('conceptName')?.setValue('');
  }

  reevaluate(): void {
    const title = this.taskForm.get('title')?.value;
    const concept = 'Anweisungen und Ausdrücke';
    let answers = '';
    for (let i = 0; i < this.getOptions().length; i++) {
      const otherOption = (this.getOptions().at(i) as FormGroup).get('text');
      answers = answers.concat(otherOption?.value + ' ');
    }
    let emptyOptions = 0;
    for (let i = 0; i < this.getOptions().length; i++) {
      const option = this.getOptions().at(i) as FormGroup;
      if (!option.get('text')?.value) {
        emptyOptions++;
      }
    }
    if (title) {
      for (let i = 0; i < this.getOptions().length; i++) {
        const option = this.getOptions().at(i) as FormGroup;
        this.fetchingStates[i] = !option.get('text')?.value;
      }
      this.mcqService
        .getReevaluatedQuestionAndAnswers(title, emptyOptions, concept, answers)
        .subscribe((answers: { mcq: McqGenerationDTO; reasoning: string }) => {
          this.reevaluatedQuestionAndAnswers$ = of([answers]);
          this.reevaluatedQuestionAndAnswers$.subscribe(answers => {
            let answerIndex = 0;
            for (let i = 0; i < this.getOptions().length; i++) {
              const option = this.getOptions().at(i) as FormGroup;
              if (!option.get('text')?.value) {
                option.get('text')?.setValue(answers[answerIndex].mcq.answers?.[i].answer);
                option.get('correct')?.setValue(answers[answerIndex].mcq.answers?.[i].correct);
                answerIndex++;
              }
              this.fetchingStates[i] = false;
            }
          });
        });
    }
  }

  openDialog(): void {
    const dialogRef = this.dialog.open(MCScoreComponent, {
      height: '270px',
      width: '270px',
      data: { score: this.taskForm.get('score')?.value },
    });

    dialogRef.afterClosed().subscribe(result => {
      this.taskForm.get('score')?.setValue(result);
    });
  }

  openDescripDialog(): void {
    const dialogRef = this.dialog.open(MCDescriptionDialogComponent, {
      height: '320px',
      width: '320px',
      data: { description: this.taskForm.get('description')?.value },
    });

    dialogRef.afterClosed().subscribe(result => {
      this.taskForm.get('description')?.setValue(result);
    });
  }

  onCheckboxChange(event: MatCheckboxChange): void {
    this.isSC = event.checked ? 'MC' : 'SC';
  }

  getCorrectOptionsCount(): number {
    return this.getOptions()
      .value.map((option: { correct: boolean }) => option.correct)
      .filter((v: boolean) => v).length;
  }

  countCorrectOptions(): void {
    let correctOptions = 0;
    for (const option of this.mcOptions) {
      if (option.correct) {
        correctOptions++;
      }
    }

    if (correctOptions >= 2) {
      this.mcDisabled = true;
    }
  }

  onSubmit(): void {
    if (this.taskForm.valid) {
      const formQuestionData: QuestionDTO = {
        author: 1,
        description: this.taskForm.get('description')?.value,
        score: this.taskForm.get('score')?.value,
        type: this.taskForm.get('type')?.value,
        text: this.taskForm.get('title')?.value,
        conceptNodeName: this.taskForm.get('conceptName')?.value,
      } as QuestionDTO;

      this.mcOptions = this.taskForm.get('options')?.value;

      this.questionService.createOptions(this.mcOptions).subscribe(options => {
        this.mcOptions = options;
      });

      this.questionService
        .createQuestion(formQuestionData)
        .pipe(
          switchMap((questionResponse: QuestionDTO): Observable<McQuestionDTO> => {
            if (questionResponse.id) {
              this.mcQuestion.questionId = questionResponse.id;
              this.mcQuestion.shuffleOptions = true;
              return this.questionService.createMcQuestion(this.mcQuestion);
            } else {
              throw new Error('QuestionVersionId is undefined');
            }
          }),
        )
        .subscribe((mcQuestion: McQuestionDTO) => {
          this.mcOptions.forEach(option => {
            this.mcQuestionOption.mcQuestion = mcQuestion;
            this.mcQuestionOption.option = option;
            this.questionService.createMcQuestionOption(this.mcQuestionOption).subscribe();
          });
        });

      this.resetTaskForm();
      this._snackBar.open('Saved a new Question', 'Close', {
        duration: 5000,
      });
    }
  }

  resetTaskForm(): void {
    const questionValue = this.taskForm.get('title')?.value;
    this.taskForm.reset();
    this.taskForm.get('title')?.setValue(questionValue);
  }

  evaluate(): void {
    const title = this.taskForm.get('title')?.value;
    const answers = this.getOptions()
      .controls.map((control: AbstractControl) => (control as FormGroup).get('text')?.value)
      .filter((text: string | null | undefined) => text);

    if (title && answers.length > 0) {
      this.mcqService.getEvaluation(title, answers).subscribe({
        next: (evalData: McqEvaluations) => {
          if (evalData.evaluations) {
            evalData.evaluations.forEach((evaluation: McqEvaluation, index: number) => {
              const option = this.getOptions().at(index) as FormGroup;
              if (evaluation.correct !== undefined) {
                option.get('correct')?.setValue(evaluation.correct);
              }
            });
          }
        },
        error: (error: any) => {
          console.error('Error evaluating answers:', error);
        },
      });
    }
  }
}
