import { BaseMessage } from '@langchain/core/messages';
import { StateGraphArgs } from '@langchain/langgraph';
import { z } from 'zod';

/**
 * Represents the shared state within the feedback LangGraph.
 */
export interface FeedbackGraphState {
  /** The history of messages in the conversation. */
  messages: BaseMessage[];
  /** Output from the compiler, if any. */
  compilerOutput: string | null;
  /** Results from unit tests, if any. */
  unitTestResults: any | null; // TODO: Define a more specific type if possible
  /** The student's submitted code solution. */
  studentSolution: string;
  /** The description of the programming task. */
  taskDescription: string;
  /** The number of attempts the student has made for this task. */
  attemptCount: number;
  /** The feedback text generated by the last executed feedback agent. */
  feedbackOutput: string | null;
  // Optional Future: studentActionsSummary?: string | null;
}

/**
 * Zod schema for validating the FeedbackGraphState.
 * Used by the LangGraph supervisor.
 */
export const zodSchema = z.object({
  messages: z.array(z.custom<BaseMessage>()), // BaseMessage doesn't have a direct Zod schema
  compilerOutput: z.string().nullable(),
  unitTestResults: z.any().nullable(), // TODO: Align with specific type if defined
  studentSolution: z.string(),
  taskDescription: z.string(),
  attemptCount: z.number().int().min(0),
  feedbackOutput: z.string().nullable(),
});

// Type helper for the state object expected by LangGraph components
export type State = z.infer<typeof zodSchema>;
