version: '3'
services:
  languageserver-java:
    image: codingame/languageserver-java:4.2.0
    ports:
      - "5007:5007"
    networks:
      - npm-network

networks:
  npm-network:
    external: true
