all: codegame

codegame: main.cpp World.cpp Actor.cpp Rover.cpp SystemOutput.cpp Destination.cpp Obstacle.cpp
	$(CXX) -std=c++11 -g -o codegame main.cpp World.cpp Actor.cpp Rover.cpp SystemOutput.cpp Destination.cpp Obstacle.cpp

clean:
	 rm -rf codegame codegame.dSYM *~
