version: '3.8' # Verwenden Sie eine geeignete Version für Ihre Bedürfnisse

services:
  python-language-server:
    image: python-language-server # Der Name des Images, das durch docker build erstellt wurde
    build: 
      context: . # Gibt das Verzeichnis des Dockerfile an (aktuelles Verzeichnis)
      dockerfile: Dockerfile # Optional, falls das Dockerfile nicht Dockerfile heißt
    ports:
      - "30001:30001" # Mappt den Port des Containers auf den Port des Hosts
    command: ["npm", "run", "start:server:python"] # Überschreibt den CMD der Dockerfile
    networks:
      - npm-network

networks:
  npm-network:
    external: true
