postgresql_databases:
        - name: production
          hostname: 172.19.0.6
          port: 5432
          username: root
          password: qzx5vQG9WQ2b35eZUWujPUhVb8xRr
          pg_dump_command: docker exec postgres_vector pg_dump
        - name: dev
          hostname: 172.19.0.6
          port: 5432
          username: root
          password: qzx5vQG9WQ2b35eZUWujPUhVb8xRr
          pg_dump_command: docker exec postgres_vector pg_dump

repositories:
    - path: ssh://jsoau056@jsoau056.repo.borgbase.com/./repo
      label: "GOALS_backup_hefl1"

exclude_patterns:
    - '*.pyc'
    - ~/*/.cache

# Stay in same file system (optional)
# one_file_system: true

compression: auto,zstd
encryption_passphrase: sijdfbhg3eq#w78rtgha+siufd
archive_name_format: 'GOALS_borgbase_{hostname}-{now:%Y-%m-%d-%H%M%S}'

# Number of times to retry a failing backup before giving up.
retries: 5
retry_wait: 5

keep_daily: 10
keep_weekly: 50
keep_monthly: 100

checks:
    - name: disabled
    # Uncomment to regularly read all repo data
    # - name: repository
    #   frequency: 4 weeks
    # - name: archives
    #   frequency: 8 weeks

check_last: 3

# Shell commands to execute before or after a backup
before_backup:
    - echo "`date` - Starting backup"

after_backup:
    - echo "`date` - Finished backup"