-- CreateTable
CREATE TABLE "genTaskData" (
    "id" SERIAL NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "topic" TEXT NOT NULL,
    "context" TEXT NOT NULL,
    "taskPrompt" TEXT,
    "task" TEXT NOT NULL,
    "expectationPrompt" TEXT,
    "expectation" TEXT NOT NULL,
    "solutionPrompt" TEXT,
    "solutionOne" TEXT NOT NULL,
    "solutionTwo" TEXT,
    "solutionThree" TEXT,
    "unitTestPrompt" TEXT,
    "unitTestOne" TEXT NOT NULL,
    "unitTestTwo" TEXT,
    "unitTestThree" TEXT,
    "errorIteration" INTEGER NOT NULL,
    "isErrorAtEnd" BOOLEAN NOT NULL,
    "errorOne" TEXT,
    "errorTwo" TEXT,
    "errorThree" TEXT,
    "juryOne" JSONB,
    "juryTwo" JSONB,
    "juryThree" JSONB,
    "codeFramework" TEXT NOT NULL,
    "runMethod" TEXT,
    "runMethodInput" TEXT,
    "allTaskData" JSONB,
    "judgeTask" JSONB,

    CONSTRAINT "genTaskData_pkey" PRIMARY KEY ("id")
);
