import {
  Controller,
  Get,
  Delete,
  Param,
  NotFoundException,
  ParseIntPipe
} from '@nestjs/common';
import { QuestionService } from './question.service';
import { CodingQuestionDto, QuestionDTO } from '@DTOs/index';

@Controller('questions')
export class QuestionController {
  constructor(private readonly questionService: QuestionService) {}

  // Note: Creation and Update routes are not implemented
  // as they are currently only generated by seed.ts

  /**
   * Find All Questions
   *
   * Handle GET requests to retrieve all Question entities.
   *
   * @route {GET} /questions
   * @returns {Promise<QuestionDTO[]>} A promise that resolves with an array of QuestionDto.
   */
  @Get()
  async findAll(): Promise<QuestionDTO[]> {
    return await this.questionService.findAll();
  }

  /**
   * Find One Question by ID
   *
   * Handle GET requests to retrieve a single Question entity based on its ID.
   *
   * @route {GET} /questions/:id
   * @param {number} id The ID of the desired question.
   * @throws {NotFoundException} Throws an exception if a question with the provided ID is not found.
   * @returns {Promise<QuestionDTO>} A promise that resolves with a QuestionDto object.
   */
  @Get(':id')
  async findOne(@Param('id', ParseIntPipe) id: number): Promise<QuestionDTO> {
    const question = await this.questionService.findOne(id);
    if (!question) {
      throw new NotFoundException(`Question with ID ${id} not found`);
    }
    return question;
  }

  /**
   * @description Retrieve a specific coding question by its ID.
   * @route GET /codingQuestion/{id}
   * @param {number} id - The ID of the coding question.
   * @returns {Promise<CodingQuestionDto>} A single coding question data transfer object.
   */
  @Get('codingQuestion/:id')
  async findCodingQuestionById(
    @Param('id') id: number,
  ): Promise<CodingQuestionDto> {
    return await this.questionService.findCodingQuestionDtoById(id);
  }

  /**
   * Remove Question by ID
   *
   * Handle DELETE requests to remove a single Question entity based on its ID.
   *
   * @route {DELETE} /questions/:id
   * @param {number} id The ID of the question to be deleted.
   * @throws {NotFoundException} Throws an exception if a question with the provided ID is not found.
   * @returns {Promise<void>} A promise that resolves when the question is deleted, or rejects with an error.
   */

  /** Aus Sicherheitsgründen erst mal entfernt.
  @Delete(':id')
  async remove(@Param('id') id: number): Promise<void> {
    const question = await this.questionService.findOne(id);
    if (!question) {
      throw new NotFoundException(`Question with ID ${id} not found`);
    }
    await this.questionService.remove(id);
  }
  */
}
